{
 "title": "Prometheus Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(up{job=\"myself\"},instance)"
   }
  ]
 },
 "panels": [
  { "title": "Prometheus Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Compaction Errors per Second (Last Hour)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compactions_failed_total{job=\"myself\"}[1h])"
    }
   ]
  },
  {
   "title": "WAL Corruptions per Second (Last Hour)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_wal_corruptions_total{job=\"myself\"}[1h])"
    }
   ]
  },
  {
   "title": "Rule Evaluations Errors per Second (Last Hour)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(prometheus_rule_evaluation_failures_total{job=\"myself\"}[1h])"
    }
   ]
  },
  {
   "title": "Prometheus Last Configuration Reload",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "prometheus_config_last_reload_successful{job=\"myself\"}"
    }
   ]
  },
  {
   "title": "Systemd Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"prometheus.service\", instance=~\"$instance.*\", state=\"active\"}"
    }
   ]
  },
  {
   "title": "Container Mountpoint Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$instance.*\", device=\"/dev/vda1\"}"
    }
   ]
  },
  {
   "title": "Active Time Series",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{job=\"myself\"}"
    }
   ]
  },
  {
   "title": "Head Block Retention",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "prometheus_tsdb_head_max_time_seconds{job=\"myself\"} - prometheus_tsdb_head_min_time_seconds{job=\"myself\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "(sum(rate(process_cpu_seconds_total{job=\"myself\"}[5m])) / count(node_cpu_seconds_total{instance=~\"$instance.*\", mode=\"idle\"})) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 5 },
   "targets": [
    {
     "expr": "(process_virtual_memory_bytes{job=\"myself\"} / ignoring (instance, job) node_memory_MemTotal_bytes{instance=~\"$instance.*\"}) * 100"
    }
   ]
  },
  {
   "title": "RSS Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "(process_resident_memory_bytes{job=\"myself\"} / ignoring (instance, job) node_memory_MemTotal_bytes{instance=~\"$instance.*\"}) * 100"
    }
   ]
  },
  {
   "title": "Container Mountpoint Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "((node_filesystem_size_bytes{instance=~\"$instance.*\", device=\"/dev/vda1\"} - node_filesystem_avail_bytes{instance=~\"$instance.*\", device=\"/dev/vda1\"}) / node_filesystem_size_bytes{instance=~\"$instance.*\", device=\"/dev/vda1\"}) * 100"
    }
   ]
  },
  {
   "title": "Samples Ingested per second",
   "type": "singlestat",
   "description": "Samples Ingested per second through scraping activity",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total{job=\"myself\"}[5m])"
    }
   ]
  },
  {
   "title": "Active Data Blocks",
   "type": "singlestat",
   "description": "Number of currently loaded data blocks",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "prometheus_tsdb_blocks_loaded{job=\"myself\"}"
    }
   ]
  },
  {
   "title": "Average Sample Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compaction_chunk_size_bytes_sum{job=\"myself\"}[1h]) / rate(prometheus_tsdb_compaction_chunk_samples_sum{job=\"myself\"}[1h])"
    }
   ]
  },
  {
   "title": "Expected Storage Dimensioning (15d)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 9 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(rate(prometheus_tsdb_compaction_chunk_size_bytes_sum{job=\"myself\"}[1h]) / rate(prometheus_tsdb_compaction_chunk_samples_sum{job=\"myself\"}[1h])) * (rate(prometheus_tsdb_head_samples_appended_total{job=\"myself\"}[5m])) * 1296000 * 1.2"
    }
   ]
  },
  {
   "title": "Expected Memory Dimensioning",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 9 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(rate(prometheus_tsdb_compaction_chunk_size_bytes_sum{job=\"myself\"}[1h]) / rate(prometheus_tsdb_compaction_chunk_samples_sum{job=\"myself\"}[1h])) * (rate(prometheus_tsdb_head_samples_appended_total{job=\"myself\"}[5m])) * 43200"
    }
   ]
  },
  {
   "title": "Active Time Series",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{job=\"myself\"}"
    }
   ]
  },
  {
   "title": "Average Sample Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compaction_chunk_size_bytes_sum{job=\"myself\"}[6h]) / rate(prometheus_tsdb_compaction_chunk_samples_sum{job=\"myself\"}[6h])"
    }
   ]
  },
  {
   "title": "Failures Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "TSDB Failures",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_reloads_failures_total{job=\"myself\"}[5m])",
       "legendFormat": "TSDB Reload Failures"
      },
      {
       "expr": "increase(prometheus_tsdb_compactions_failed_total{job=\"myself\"}[5m])",
       "legendFormat": "TSDB Compaction Failures"
      }
     ]
    },
    {
     "title": "WAL and TSDB Head Failures",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_checkpoint_creations_failed_total{job=\"myself\"}[5m])",
       "legendFormat": "Checkpoint Creation Failures"
      },
      {
       "expr": "increase(prometheus_tsdb_checkpoint_deletions_failed_total{job=\"myself\"}[5m])",
       "legendFormat": "Checkpoint Deletion Failures"
      },
      {
       "expr": "increase(prometheus_tsdb_head_truncations_failed_total{job=\"myself\"}[5m])",
       "legendFormat": "Head Truncation Failures"
      },
      {
       "expr": "increase(prometheus_tsdb_wal_truncations_failed_total{job=\"myself\"}[5m])",
       "legendFormat": "WAL Truncation Failures"
      },
      {
       "expr": "increase(prometheus_tsdb_wal_corruptions_total{job=\"myself\"}[5m])",
       "legendFormat": "WAL Corruptions "
      }
     ]
    },
    {
     "title": "Notification Failures",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(prometheus_template_text_expansion_failures_total{job=\"myself\"}[5m])",
       "legendFormat": "Text Expansion in Notifications"
      },
      {
       "expr": "increase(prometheus_notifications_dropped_total{job=\"myself\"}[5m])",
       "legendFormat": "Notifications Dropped"
      },
      {
       "expr": "increase(prometheus_notifications_errors_total{job=\"myself\"}[5m])",
       "legendFormat": "Notification Sending Errors"
      }
     ]
    },
    {
     "title": "Notification Queue",
     "type": "graph",
     "description": "If length approaches limit, notifications may be lost",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "prometheus_notifications_queue_length{job=\"myself\"}",
       "legendFormat": "Notifications Queue Length"
      },
      {
       "expr": "prometheus_notifications_queue_capacity{job=\"myself\"}",
       "legendFormat": "Notifications Queue Limit"
      }
     ]
    },
    {
     "title": "Rule Evaluation Failures",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(prometheus_rule_evaluation_failures_total{job=\"myself\"}[5m])",
       "legendFormat": "Rule Evaluation Failures"
      }
     ]
    },
    {
     "title": "Service Discovery Failures",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(prometheus_sd_consul_rpc_failures_total{job=\"myself\"}[5m])",
       "legendFormat": "SD Consul RPC Failures"
      },
      {
       "expr": "increase(prometheus_sd_dns_lookup_failures_total{job=\"myself\"}[5m])",
       "legendFormat": "SD DNS Lookup Failures"
      },
      {
       "expr": "increase(prometheus_sd_refresh_failures_total{mechanism=\"dns\", job=\"myself\"}[5m])",
       "legendFormat": "SD DNS Refresh Failures"
      },
      {
       "expr": "increase(prometheus_sd_file_read_errors_total{job=\"myself\"}[5m])",
       "legendFormat": "SD File Read Errors"
      },
      {
       "expr": "prometheus_sd_failed_configs{name=\"scrape\", job=\"myself\"}",
       "legendFormat": "SD Configuration Load Failure"
      }
     ]
    },
    {
     "title": "Scrape Pool Failures",
     "type": "graph",
     "description": "Forced Scrape Cache Flushes: How many times a scrape cache was flushed due to getting big while scrapes are failing.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(prometheus_target_scrape_pool_reloads_failed_total{job=\"myself\"}[5m])",
       "legendFormat": "Scrape Pool Reload Failures"
      },
      {
       "expr": "increase(prometheus_target_scrape_pools_failed_total{job=\"myself\"}[5m])",
       "legendFormat": "Scrape Pool Creation Failures"
      },
      {
       "expr": "increase(prometheus_target_scrapes_cache_flush_forced_total{job=\"myself\"}[5m])",
       "legendFormat": "Forced Scrape Cache Flushes"
      }
     ]
    },
    {
     "title": "Samples Rejected",
     "type": "graph",
     "description": "Sample limit is defined by configuration, it is not by default",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(prometheus_target_scrapes_sample_duplicate_timestamp_total{job=\"myself\"}[5m])",
       "legendFormat": "Duplicated Timestamps"
      },
      {
       "expr": "increase(prometheus_target_scrapes_sample_out_of_bounds_total{job=\"myself\"}[5m])",
       "legendFormat": "Timestamp Out-of-Bounds"
      },
      {
       "expr": "increase(prometheus_target_scrapes_sample_out_of_order_total{job=\"myself\"}[5m])",
       "legendFormat": "Sample Out-of-Order"
      },
      {
       "expr": "increase(prometheus_target_scrapes_exceeded_sample_limit_total{job=\"myself\"}[5m])",
       "legendFormat": "Sample Limit Exceeded"
      }
     ]
    },
    {
     "title": "Rule Groups Failures",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(prometheus_rule_group_iterations_missed_total{job=\"myself\"}[5m])",
       "legendFormat": "Rule Group Evaluations Missed "
      }
     ]
    },
    {
     "title": "Last Evaluation / Interval Evaluation Ratio",
     "type": "graph",
     "description": "If close or bigger than 1, the last evaluation of a group of rules took longer that its interval evaluation",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "prometheus_rule_group_last_duration_seconds{job=\"myself\"} / on (rule_group) prometheus_rule_group_interval_seconds{job=\"myself\"}",
       "legendFormat": "Last Evaluation / Interval Evaluation of Group {{ rule_group }}"
      }
     ]
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Prometheus CPU Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"myself\"}[5m])",
     "legendFormat": "CPU Cores Used by Prometheus (irate)"
    },
    {
     "expr": "rate(process_cpu_seconds_total{job=\"myself\"}[5m])",
     "legendFormat": "CPU Cores Used by Prometheus (rate)"
    },
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"$instance.*\", mode=\"idle\"})",
     "legendFormat": "CPU Cores Limit"
    }
   ]
  },
  {
   "title": "Prometheus Process Memory Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"myself\"}",
     "legendFormat": "Prometheus RSS Memory"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"myself\"}",
     "legendFormat": "Prometheus Virtual Memory"
    },
    {
     "expr": "go_memstats_alloc_bytes{job=\"myself\"} + go_memstats_stack_inuse_bytes{job=\"myself\"}",
     "legendFormat": "Prometheus Go Memory Allocated and In Use"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance.*\"}",
     "legendFormat": "Container Memory Limit"
    }
   ]
  },
  {
   "title": "Disk Space Utilization (Stacked)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~\"$instance.*\", device=\"/dev/vda1\"} - node_filesystem_avail_bytes{instance=~\"$instance.*\", device=\"/dev/vda1\"})",
     "legendFormat": "Used Disk Space"
    },
    {
     "expr": "node_filesystem_avail_bytes{instance=~\"$instance.*\", device=\"/dev/vda1\"}",
     "legendFormat": "Free Disk Space"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$instance.*\", device=\"/dev/vda1\"}",
     "legendFormat": "Total Disk Space"
    }
   ]
  },
  {
   "title": "Time Before Running Out Of Space (Experimental)",
   "type": "graph",
   "description": "Experimental",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=~\"$instance.*\", device=\"/dev/vda1\"}/\nclamp_min((node_filesystem_avail_bytes{instance=~\"$instance.*\", device=\"/dev/vda1\"} - \npredict_linear(node_filesystem_avail_bytes{instance=~\"$instance.*\", device=\"/dev/vda1\"}[1h], 1 * 3600)),0)\n",
     "legendFormat": "Time Left on {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Storage (TSDB) Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Chunk Time",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 23 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_compaction_chunk_range_seconds_sum{job=\"myself\"}[6h])/rate(prometheus_tsdb_compaction_chunk_range_seconds_count{job=\"myself\"}[6h])"
      }
     ]
    },
    {
     "title": "Samples Per Chunk",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 23 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_compaction_chunk_samples_sum{job=\"myself\"}[6h])/rate(prometheus_tsdb_compaction_chunk_samples_count{job=\"myself\"}[6h])",
       "legendFormat": "series"
      }
     ]
    },
    {
     "title": "Avg Chunk Size",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 23 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_compaction_chunk_size_bytes_sum{job=\"myself\"}[6h])/rate(prometheus_tsdb_compaction_chunk_size_bytes_count{job=\"myself\"}[6h])",
       "legendFormat": "series"
      }
     ]
    },
    {
     "title": "Bytes/Sample",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 23 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "(rate(prometheus_tsdb_compaction_chunk_size_bytes_sum{job=\"myself\"}[6h])/rate(prometheus_tsdb_compaction_chunk_size_bytes_count{job=\"myself\"}[6h]))/(rate(prometheus_tsdb_compaction_chunk_samples_sum{job=\"myself\"}[6h])/rate(prometheus_tsdb_compaction_chunk_samples_count[6h]))",
       "legendFormat": "series"
      }
     ]
    },
    {
     "title": "Head Block Size",
     "type": "singlestat",
     "description": "Head Block Size (Estimated)",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 23 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_compaction_chunk_size_bytes_sum{job=\"myself\"}[6h])/rate(prometheus_tsdb_compaction_chunk_size_bytes_count{job=\"myself\"}[6h])*(prometheus_tsdb_head_chunks{job=\"myself\"})",
       "legendFormat": "series"
      }
     ]
    },
    {
     "title": "Avg Compaction Time",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 23 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_compaction_duration_seconds_sum{job=\"myself\"}[6h])/rate(prometheus_tsdb_compaction_duration_seconds_count{job=\"myself\"}[6h])"
      }
     ]
    },
    {
     "title": "WAL Fsync Time",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 23 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_wal_fsync_duration_seconds_sum{job=\"myself\"}[6h])/rate(prometheus_tsdb_wal_fsync_duration_seconds_count{job=\"myself\"}[6h])"
      }
     ]
    },
    {
     "title": "Head GC Latency",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 21, "y": 23 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_gc_duration_seconds_sum{job=\"myself\"}[6h])/rate(prometheus_tsdb_head_gc_duration_seconds_count{job=\"myself\"}[6h])"
      }
     ]
    },
    {
     "title": "Compactions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_compactions_total{job=\"myself\"}[2h])",
       "legendFormat": "Compactions Performed"
      },
      {
       "expr": "increase(prometheus_tsdb_compactions_failed_total{job=\"myself\"}[2h]) ",
       "legendFormat": "Compactions Failed"
      },
      {
       "expr": "prometheus_tsdb_compactions_total{job=\"myself\"}",
       "legendFormat": "Counter"
      }
     ]
    },
    {
     "title": "WAL Failures",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_wal_corruptions_total{job=\"myself\"}[2h])",
       "legendFormat": "WAL Corruptions"
      },
      {
       "expr": "increase(prometheus_tsdb_wal_truncations_failed_total{job=\"myself\"}[2h]) ",
       "legendFormat": "WAL Truncation Failures"
      }
     ]
    },
    {
     "title": "Active Data Blocks",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "prometheus_tsdb_blocks_loaded{job=\"myself\"}",
       "legendFormat": "Active (Loaded) Data Blocks"
      }
     ]
    },
    {
     "title": "Head Block",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "prometheus_tsdb_head_chunks{job=\"myself\"}",
       "legendFormat": "Chunks"
      },
      {
       "expr": "prometheus_tsdb_head_series{job=\"myself\"}",
       "legendFormat": "Series "
      },
      {
       "expr": "rate(prometheus_tsdb_compaction_chunk_size_bytes_sum{job=\"myself\"}[6h])/rate(prometheus_tsdb_compaction_chunk_size_bytes_count{job=\"myself\"}[6h])*(prometheus_tsdb_head_chunks{job=\"myself\"})",
       "legendFormat": "Size (Estimated)"
      }
     ]
    },
    {
     "title": "Chunk Activity",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_chunks_created_total{job=\"myself\"}[1h])",
       "legendFormat": "Chunks Created"
      },
      {
       "expr": "rate(prometheus_tsdb_head_chunks_removed_total{job=\"myself\"}[1h])",
       "legendFormat": "Chunks Removed"
      }
     ]
    },
    {
     "title": "Reload block data from disk",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_reloads_total{job=\"myself\"}[1h]) - rate(prometheus_tsdb_reloads_failures_total{job=\"myself\"}[1h])",
       "legendFormat": "Success"
      },
      {
       "expr": "rate(prometheus_tsdb_reloads_failures_total{job=\"myself\"}[1h])",
       "legendFormat": "Failures"
      }
     ]
    }
   ]
  },
  {
   "title": "Time Series Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 metrics by time series count",
     "type": "table",
     "description": "10 Highest Cardinality Metrics",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "topk(10, count({__name__=~\".+\"})  by (__name__))",
       "legendFormat": "{{ __name__ }}"
      }
     ]
    },
    {
     "title": "Top 10 hosts by time series count",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "expr": "topk(10, count(label_replace({__name__=~\".+\"}, \"instance\", \"$1\", \"instance\", \"(.*):.*\"))  by (instance))",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Scraping",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ingestion",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(prometheus_target_interval_length_seconds_count[5m]))",
       "legendFormat": "Scrapes Performed"
      },
      {
       "expr": "rate(prometheus_tsdb_head_samples_appended_total[5m])",
       "legendFormat": "Samples appended in the head block (Samples per second)"
      }
     ]
    },
    {
     "title": "Prometheus Targets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "count(up)", "legendFormat": "Targets Configured" },
      {
       "expr": "sum(avg_over_time(up[5m]))",
       "legendFormat": "Avg Succesfully Scraped Targets"
      },
      {
       "expr": "sum(min_over_time(up[5m]))",
       "legendFormat": "Min Successfully Scraped Targets"
      }
     ]
    },
    {
     "title": "Scraped Target by Job",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(avg_over_time(up[5m])) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Scrape Time by Job",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(avg_over_time(scrape_duration_seconds[5m])) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Scraped Target by Instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(avg_over_time(up[5m]), \"instance\", \"$1\", \"instance\", \"(.*):.*\")) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Scrape Time by Instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(label_replace(avg_over_time(scrape_duration_seconds[5m]), \"instance\", \"$1\", \"instance\", \"(.*):.*\")) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Scrapes by Target Frequency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_target_interval_length_seconds_count[5m])",
       "legendFormat": "Rate of {{interval}} scrapes"
      }
     ]
    },
    {
     "title": "Scrape Frequency Versus Target",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(rate(prometheus_target_interval_length_seconds_sum[5m]) / rate(prometheus_target_interval_length_seconds_count[5m]))",
       "legendFormat": "Actual  {{interval}} scrape interval  length"
      }
     ]
    },
    {
     "title": "Scraping Time Drift",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      { "expr": "time() - node_time_seconds", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Prometheus Scrape Interval Variance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(sum(prometheus_target_interval_length_seconds{interval=\"5s\",job=\"myself\",quantile=\"0.99\"}) by () - sum(prometheus_target_interval_length_seconds{interval=\"5s\",job=\"myself\",quantile=\"0.01\"}) by ())/5",
       "legendFormat": "5sec Target Interval Variance"
      },
      {
       "expr": "(sum(prometheus_target_interval_length_seconds{interval=\"10s\",job=\"myself\",quantile=\"0.99\"}) by () - sum(prometheus_target_interval_length_seconds{interval=\"10s\",job=\"myself\",quantile=\"0.01\"}) by ())/10",
       "legendFormat": "1sec  Target Interval Variance"
      },
      {
       "expr": "(sum(prometheus_target_interval_length_seconds{interval=\"15s\",job=\"myself\",quantile=\"0.99\"}) by () - sum(prometheus_target_interval_length_seconds{interval=\"15s\",job=\"myself\",quantile=\"0.01\"}) by ())/15",
       "legendFormat": "1min Target Interval Variance"
      }
     ]
    },
    {
     "title": "Slowest Jobs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(10,max_over_time(scrape_duration_seconds[5m]))",
       "legendFormat": "{{job}} at {{instance}}"
      }
     ]
    },
    {
     "title": "Largest Samples Jobs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10,max_over_time(scrape_samples_scraped[5m]))",
       "legendFormat": "{{job}} at {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average HTTP Requests Average Duration by Handler",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_http_request_duration_seconds_sum{job=\"myself\"}[5m]) / rate(prometheus_http_request_duration_seconds_count{job=\"myself\"}[5m])",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "HTTP Response Average Size by Handler",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_http_response_size_bytes_sum{job=\"myself\"}[5m]) / rate(prometheus_http_response_size_bytes_count{job=\"myself\"}[5m])",
       "legendFormat": "{{handler}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus Queries",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "prometheus_engine_queries_concurrent_max{job=\"myself\"}",
       "legendFormat": "Maximum Queries Permitted"
      },
      {
       "expr": "avg_over_time(prometheus_engine_queries{job=\"myself\"}[5m])",
       "legendFormat": "Avg Queries Active"
      },
      {
       "expr": "max_over_time(prometheus_engine_queries{job=\"myself\"}[5m])",
       "legendFormat": "Max Queries Active"
      }
     ]
    },
    {
     "title": "Prometheus Query Execution",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_engine_query_duration_seconds_count{job=\"myself\"}[5m])",
       "legendFormat": "{{slice}} - Executed"
      }
     ]
    },
    {
     "title": "Prometheus Query Execution Latency (Stacked)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(rate(prometheus_engine_query_duration_seconds_sum{job=\"myself\"}[5m])/rate(prometheus_engine_query_duration_seconds_count{job=\"myself\"}[5m]))",
       "legendFormat": "{{slice}} - Avg. Time"
      }
     ]
    },
    {
     "title": "Prometheus Query Execution Load (Stacked)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_engine_query_duration_seconds_sum{job=\"myself\"}[5m])",
       "legendFormat": "{{slice}} - Load"
      }
     ]
    }
   ]
  }
 ]
}